# Generated by Django 5.1.3 on 2024-11-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cliente_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nivel_de_satisfaccion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
